# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FCU40y7zbYTL1VhZIl0eZNBPhoDyK1rZ
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# 1. Load the Dataset (Use a Spotify Top 50 dataset from Kaggle)
# Make sure to include the dataset file in your final ZIP [cite: 12, 15]

# --- Start of fix for FileNotFoundError ---
try:
    df = pd.read_csv('Dataset.csv', encoding='ISO-8859-1')
except FileNotFoundError:
    print("Error: 'Dataset.csv' not found. Please ensure the dataset file is uploaded to your Colab environment or the correct path is provided.")
    print("For a Spotify Top 50 dataset from Kaggle, you would typically download it from Kaggle and upload it here (e.g., using `files.upload()` or the file browser).")
    print("Proceeding with a dummy DataFrame for demonstration. Please replace with your actual data to get meaningful results.")

    # Create a dummy DataFrame with expected column names (before cleaning)
    dummy_data = {
        'Track.Name': ['Shallow', 'Blinding Lights', 'Dance Monkey', 'Circles', 'Old Town Road'],
        'Artist.Name': ['Lady Gaga', 'The Weeknd', 'Tones and I', 'Post Malone', 'Lil Nas X'],
        'Genre': ['Pop', 'R&B', 'Pop', 'Hip Hop', 'Country Rap'],
        'Beats.Per.Minute': [96, 171, 98, 120, 136],
        'Energy': [57, 80, 59, 71, 62],
        'Danceability': [64, 51, 82, 76, 88],
        'Loudness..dB.': [-6, -4, -6, -5, -7],
        'Liveness': [10, 12, 18, 9, 7],
        'Valence': [37, 34, 54, 71, 64],
        'Length.': [215, 201, 209, 203, 157],
        'Acousticness..': [23, 0, 71, 15, 5],
        'Speechiness': [3, 6, 8, 4, 10],
        'Popularity': [85, 95, 90, 88, 92]
    }
    df = pd.DataFrame(dummy_data)
# --- End of fix for FileNotFoundError ---


# 2. Data Cleaning
df.columns = df.columns.str.replace('.', '_').str.lower()
df.dropna(inplace=True)

# --- 10 Visualizations  ---

# 1. Popularity Distribution
plt.figure(figsize=(10, 5))
sns.histplot(df['popularity'], bins=15, kde=True, color='green')
plt.title('Distribution of Song Popularity')
plt.show()

# 2. Top 10 Artists
plt.figure(figsize=(10, 5))
df['artist_name'].value_counts().head(10).plot(kind='bar', color='skyblue')
plt.title('Top 10 Artists with Most Hits')
plt.ylabel('Count of Songs')
plt.show()

# 3. Genre Dominance
plt.figure(figsize=(10, 5))
sns.countplot(y='genre', data=df, order=df['genre'].value_counts().index)
plt.title('Most Popular Genres')
plt.show()

# 4. Danceability vs Energy (Scatter Plot)
plt.figure(figsize=(10, 5))
sns.scatterplot(x='danceability', y='energy', data=df, hue='popularity', size='popularity')
plt.title('Danceability vs Energy Correlation')
plt.show()

# 5. Acousticness by Genre (Box Plot)
plt.figure(figsize=(12, 6))
sns.boxplot(x='genre', y='acousticness__', data=df)
plt.xticks(rotation=45)
plt.title('Acousticness Levels Across Genres')
plt.show()

# 6. Tempo (BPM) Histogram
plt.figure(figsize=(10, 5))
sns.histplot(df['beats_per_minute'], bins=10, color='orange')
plt.title('Common Beats Per Minute (BPM) Ranges')
plt.show()

# 7. Loudness vs Popularity
plt.figure(figsize=(10, 5))
sns.regplot(x='loudness__db_', y='popularity', data=df, color='red')
plt.title('Impact of Loudness on Popularity')
plt.show()

# 8. Valence vs Danceability
plt.figure(figsize=(10, 5))
sns.jointplot(x='valence', y='danceability', data=df, kind='hex', color='purple')
plt.suptitle('Valence (Mood) vs Danceability', y=1.02)
plt.show()

# 9. Speechiness Comparison
plt.figure(figsize=(10, 5))
sns.violinplot(x='genre', y='speechiness', data=df)
plt.xticks(rotation=45)
plt.title('Speechiness Variance Across Genres')
plt.show()

# 10. Liveness vs Energy
plt.figure(figsize=(10, 5))
sns.kdeplot(x=df['liveness'], y=df['energy'], cmap="Reds", fill=True)
plt.title('Density Plot: Liveness vs Energy')
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# 1. Load the Dataset
df = pd.read_csv('Dataset.csv', encoding='ISO-8859-1')

# 2. Data Cleaning - This part is crucial to make column names easier to use
# We will rename the messy CSV columns to clean names
clean_columns = {
    'Track.Name': 'track',
    'Artist.Name': 'artist',
    'Genre': 'genre',
    'Beats.Per.Minute': 'bpm',
    'Energy': 'energy',
    'Danceability': 'danceability',
    'Loudness..dB.': 'loudness',
    'Liveness': 'liveness',
    'Valence': 'valence',
    'Length.': 'length',
    'Acousticness..': 'acousticness',
    'Speechiness': 'speechiness',
    'Popularity': 'popularity'
}
df.rename(columns=clean_columns, inplace=True)

# --- 10 Visualizations (Now using the cleaned names) ---

# 1. Popularity Distribution
plt.figure(figsize=(10, 5))
sns.histplot(df['popularity'], bins=10, kde=True, color='green')
plt.title('Distribution of Song Popularity')
plt.show()

# 2. Top 10 Artists
plt.figure(figsize=(10, 5))
df['artist'].value_counts().head(10).plot(kind='bar', color='skyblue')
plt.title('Top 10 Artists with Most Hits')
plt.show()

# 3. Genre Dominance
plt.figure(figsize=(10, 5))
sns.countplot(y='genre', data=df, order=df['genre'].value_counts().index)
plt.title('Most Popular Genres')
plt.show()

# 4. Danceability vs Energy
plt.figure(figsize=(10, 5))
sns.scatterplot(x='danceability', y='energy', data=df, hue='popularity')
plt.title('Danceability vs Energy')
plt.show()

# 5. Acousticness by Genre (THE FIXED LINE)
plt.figure(figsize=(12, 6))
sns.boxplot(x='genre', y='acousticness', data=df)
plt.xticks(rotation=45)
plt.title('Acousticness Levels Across Genres')
plt.show()

# 6. Tempo (BPM) Histogram
plt.figure(figsize=(10, 5))
sns.histplot(df['bpm'], bins=10, color='orange')
plt.title('Common BPM Ranges')
plt.show()

# 7. Loudness vs Popularity
plt.figure(figsize=(10, 5))
sns.regplot(x='loudness', y='popularity', data=df, color='red')
plt.title('Impact of Loudness on Popularity')
plt.show()

# 8. Mood (Valence) vs Danceability
plt.figure(figsize=(10, 5))
sns.scatterplot(x='valence', y='danceability', data=df, color='purple')
plt.title('Valence (Mood) vs Danceability')
plt.show()

# 9. Speechiness Comparison
plt.figure(figsize=(10, 5))
sns.boxplot(x='genre', y='speechiness', data=df)
plt.xticks(rotation=45)
plt.title('Speechiness Across Genres')
plt.show()

# 10. Liveness vs Energy
plt.figure(figsize=(10, 5))
sns.kdeplot(x=df['liveness'], y=df['energy'], fill=True)
plt.title('Density Plot: Liveness vs Energy')
plt.show()

"""streamlit run app.py"""

pip install streamlit

import streamlit as st
import pandas as pd
import plotly.express as px

st.set_page_config(page_title="Spotify Dashboard", layout="wide")

# Load and Clean
@st.cache_data
def load_data():
    # Make sure your file is named exactly this
    df = pd.read_csv('Dataset.csv', encoding='ISO-8859-1')
    # This standardizes column names to avoid errors
    df.columns = df.columns.str.replace('.', '_').str.lower()
    return df

df = load_data()

st.title("🎵 Spotify Winter 2025 Analysis")
st.write("Project Dashboard by [Your Name]")

# Sidebar
st.sidebar.header("Settings")
genre_filter = st.sidebar.multiselect("Filter by Genre", options=df['genre'].unique(), default=df['genre'].unique()[:3])
filtered_df = df[df['genre'].isin(genre_filter)]

# Plot 1: Energy vs Popularity
st.subheader("Analysis 1: Energy vs Popularity")
fig1 = px.scatter(filtered_df, x="energy", y="popularity", color="genre", hover_name="track_name")
st.plotly_chart(fig1, width='stretch')

# Plot 2: Top Artists (FIXED VERSION)
st.subheader("Analysis 2: Top Artists in Selected Genres")
artist_counts = filtered_df['artist_name'].value_counts().reset_index()
# Automatically detect column names to prevent ValueErrors
artist_counts.columns = ['Artist', 'Count']

fig2 = px.bar(artist_counts, x='Artist', y='Count', color='Artist', title="Number of Hits per Artist")
st.plotly_chart(fig2, width='stretch')

# Plot 3: Popularity Distribution
st.subheader("Analysis 3: Popularity Distribution")
fig3 = px.histogram(filtered_df, x="popularity", nbins=10, color_discrete_sequence=['green'])
st.plotly_chart(fig3, width='stretch')

"""Part 1: The 10 Analytical Questions
These questions are designed to cover various data relationships (distribution, correlation, and comparison).

Popularity Distribution: How is the "Popularity" score distributed across the entire dataset?

Top 10 Artists: Which artists have the highest number of songs in the top charts?

Genre Dominance: What are the most frequent genres appearing in the dataset?

Danceability vs. Energy: Is there a correlation between how "danceable" a song is and its energy level?

Acousticness Over Time: (If year data is available) How has the use of acoustic instruments changed?

Tempo Analysis: What is the most common BPM (Beats Per Minute) range for a "hit" song?

Loudness and Popularity: Does a higher decibel level (loudness) correlate with higher popularity?

Valence (Mood) vs. Danceability: Do happier songs (high valence) tend to be more danceable?

Speechiness in Top Genres: How does the amount of spoken word vary between Rap, Pop, and Rock?

Song Duration Trends: What is the average duration of a top-charting song?
"""